### ISSUE TITLE
Coherence in what's displayed when it comes to user authentication error messages

### ISSUE THREAD

**Issue by huangzz125** [project-orbital/backend#33]
https://www.dollarplanner.live/request-password-reset
friends suggestion:
This page when u key in an email that isnt tied to an account, it throws an error, yall are prolly reading from ur database and checking if an acc exists with this email, but i think i read before its good (security/privacy concerns) practice to always just display to the user that an email is sent, because otherwise someone can know whether an email account has registered this service, which might not be a good idea all the time e.g. u create some sketchy service then ppl dont want others to know that they have signed up for it

**Comment by jontmy** [comment]
Implemented in #52.
